"""WhatUpDoc — Gradio chat interface.

    python app.py

Upload a PDF/DOCX/TXT, then ask questions. Answers are generated by a
locally hosted LLM (Ollama) and grounded strictly in the uploaded
documents, with [source, page] citations. Gradio binds to 127.0.0.1
only — the app is never exposed off-machine.
"""

from __future__ import annotations
import gradio as gr
from src.rag_pipeline import RAGPipeline
from pathlib import Path

pipeline = RAGPipeline()


def handle_upload(files: list) -> str:
    """Ingest uploaded files and report chunk counts."""
    if not files:
        return "No files received."
    messages = []
    for f in files:
        try:
            n = pipeline.ingest(f.name)
            messages.append(f"Ingested {Path(f.name).name} ({n} chunks).")
        except Exception as exc:
            messages.append(f"Failed on {Path(f.name).name}: {exc}")
    return "\n".join(messages)


def handle_question(message: str, history: list) -> str:
    """Answer a chat question with citations and source previews."""
    result = pipeline.ask(message)
    sources = "\n".join(
        f"- {s['source']}, p.{s['page_number']} (distance {s['distance']})"
        for s in result["sources"]
    )
    return f"{result['answer']}\n\n**Retrieved from:**\n{sources}" if sources else result["answer"]


with gr.Blocks(title="WhatUpDoc") as demo:
    gr.Markdown("# WhatUpDoc\n*Privacy-first document Q&A — nothing leaves your machine.*")
    with gr.Row():
        uploader = gr.File(label="Upload documents (PDF / DOCX / TXT)", file_count="multiple")
        status = gr.Textbox(label="Ingestion status", interactive=False)
    uploader.upload(handle_upload, uploader, status)
    gr.ChatInterface(fn=handle_question, examples=[
        "What is the monthly rent and when is it due?",
        "Does the patient have any allergies?",
    ])

if __name__ == "__main__":
    demo.launch(server_name="127.0.0.1", share=False)
